# -*- coding: utf-8 -*-
"""ecoVAD_chirpR_setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcB8nn-4y78YexJhfD34gsT3EZKJKY5F
"""

# Intended to be placed in project directory. ecoVAD will be added as a subdirectory.
# --- CLONE REPO ---
import os
from pathlib import Path
import subprocess


PROJ = Path('/content/drive/MyDrive/laridae')
REPO_URL = 'https://github.com/joetric/ecoVAD_chirpR'
REPO_LOCAL = PROJ / 'ecoVAD_chirpR'
ASSETS_DIR = REPO_LOCAL / 'assets'


def setup_environment():
    """Setup environment for both Colab and local use"""
    try:
        from google.colab import drive
        print("Running in Google Colab")
        drive.mount('/content/drive')
        base_path = PROJ
    except ImportError:
        print("Running locally")
        base_path = Path(__file__).parent.absolute()

    return base_path


# Use it
base_path = setup_environment()
print(f"Working directory: {base_path}")


os.chdir(PROJ)
subprocess.run(["git", "clone", REPO_URL], capture_output=True)
os.chdir(REPO_LOCAL)

# Install requirements / make requirements.txt
# uncomment next two lines to make requirements.txt
# !pip -q install numpy pandas scipy scikit-learn librosa numba torch torchaudio pipreqs
# !pipreqs /content/drive/MyDrive/laridae/ecoVAD_chirpR --force
subprocess.run(["pip", "install", "-q", "-r", f"{REPO_LOCAL}/requirements.txt"], check=True)

if not ASSETS_DIR.exists():
    print("Downloading and extracting assets...")
    subprocess.run('wget https://osf.io/yvdhf/download -O assets.zip && unzip assets.zip && rm assets.zip',
                shell=True, check=True)
else:
    print("Assets already downloaded...if there is a problem, redownload manually.")